---
title: "Personal Performance"
author: "Tobias Anton"
date: "`r ddateR::poee()`"
output:
  html_document:
    css: style.css
    fig_width: 10
    dpi: 640
    highlight: tango
    theme: spacelab
    self_contained: no
    lib_dir: "assets"
---

```{r, message=F, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.path = "highscore-plots/", warning = F, message = F)

    library(dplyr)        # f端r einfacheren Umgang mit Dataframes (wie z.B. ngo)
    library(ggplot2)      # auch Daten wollen h端bsch sein
    library(tidyr)        # schnell und einfach Dataframes manipulieren; kann gather()
    library(broom)        # macht mit tidy() sowas wie lm() und t.test() lesbarer
    library(RColorBrewer) # h端bsche Daten noch h端bscher machen
    library(googlesheets) # importing ALL the sheets!
    library(ggthemes)     # making them pretty plots even prettier
    library(viridis)      # best color palette, hands down
    library(rmdformats)   # look at them beautiful templates!
    library(sjPlot)       # a little bit analysis

    tobi <- gs_title("jinteki.net") %>% gs_read(ws = 1) %>% 
      mutate(Points = car::recode(Game, "'Loose' = 0; 'Win' = 1"))
    
    paul <- gs_title("jinteki.net") %>% gs_read(ws = 2) %>% 
      mutate(Points = car::recode(Game, "'Loss' = 0; 'Win' = 1"))
    
    falk <- gs_title("jinteki.net") %>% gs_read(ws = 3) %>% 
      mutate(Points = car::recode(Game, "'Loss' = 0; 'Win' = 1"))
```

# Tobi

```{r tobi_tbl}
tobi %>% 
  group_by(Side, Faction, ID) %>% 
  summarize("Games" = n(),
            "Wins" = sum(Points),
            "Perc" = round(Wins / Games * 100, 2)) %>% 
  knitr::kable()
```


```{r sjtbl, eval = F}
sjtbl <- sjt.xtab(
  tobi$ID, tobi$Game, 
  show.exp = T, emph.total = T, show.row.prc = T,
  use.viewer = F, no.output = T
)

<div align = "center">
`r sjtbl$knitr`
</div>
```



# Paul

```{r paul_tbl}
paul %>% 
  group_by(Side, Faction, ID) %>% 
  summarize("Games" = n(),
            "Wins" = sum(Points),
            "Perc" = round(Wins / Games * 100, 2)) %>% 
  knitr::kable()
```



# Falk

```{r falk_tbl}
falk %>% 
  group_by(Side, Faction, ID) %>% 
  summarize("Games" = n(),
            "Wins" = sum(Points),
            "Perc" = round(Wins / Games * 100, 2)) %>% 
  knitr::kable()
```