---
title: "Netrunnerliga Bremen - Season 4"
date: "`r ddateR::poee()`"
output:
  html_document
---

```{r, init, echo = F, warning = F, message = F}
source(paste0(Sys.getenv("PROJECT_HOME"), "./init.R"))
knitr::opts_chunk$set(fig.path = "assets/liga-plots/04")

s4 <- readRDS("./data/Liga.rds")
```

```
# sample code from old page
liga_04 %>% 
  group_by(Spieler) %>% 
  summarize(Spiele       = n()/2,
            Agendapunkte = sum(Agendapunkte, na.rm = T),
            Punkte       = sum(Punkte)) %>%
  arrange(desc(Punkte), desc(Agendapunkte)) %>% 
  format_table(
    list(Agendapunkte = color_tile("white", "lightgray"),
               Spiele = formatter("span", style = x ~ style(
                                    color = ifelse(x <= 4, "red", 
                                                   ifelse(x >= 7, "green", "gray"))))
         ),
    align = "l", check.rows = F, format = "markdown")
```

```{r Punktestand}
# try to replicate with new structure
## this gives accurate table of standings
s4 %>% 
  gather(Seite, Spieler, Konzern_Player, Runner_Player) %>% 
  mutate(Punkte = ifelse(Sieger_Spieler == Spieler, 3, 0)) %>% 
  group_by(Spieler) %>% 
  summarise(Spiele       = n() / 2,
            Agendapunkte = sum(Runner_Agendapunkte + Konzern_Agendapunkte),
            Gesamtpunkte = sum(Punkte)) %>% 
  arrange(desc(Gesamtpunkte), desc(Agendapunkte)) %>% 
  knitr::kable()

## this gives accurate table of played games
ftable(table(s4$Konzern_Player, s4$Runner_Player))
```


## Spielhäufigkeiten

### nach Fraktion

```{r Fraktionen}
# define colors:
all_colors <- c("darkorange", "deepskyblue3", "darkorchid4", "red", 
                "gold1", "darkgray", "chartreuse3", "darkolivegreen")
kon_colors <- c("darkorchid4", "red", "gold1", "darkolivegreen")
run_colors <- c("darkorange", "deepskyblue3", "darkgray", "chartreuse3")

# plot Factions:
data.frame(
    Seite    = c(rep("Konzern", length(s4$Konzern_Player)), 
                 rep("Runner", length(s4$Runner_Player))),
    Fraktion = c(s4$Konzern_Fraktion, s4$Runner_Fraktion)
) %>% 
  ggplot(aes(x = Fraktion, fill = Fraktion, color = Fraktion)) +
    geom_bar(alpha = .4) +
    scale_fill_manual(values = all_colors) +
    scale_color_manual(values = all_colors) +
    labs(x = "", y = "Spiele") +
    facet_wrap(~Seite, scales = "free_x", ncol = 4) +
    theme(legend.position = "none")
```

### nach ID

```{r IDs_Konzern}
ggplot(s4, aes(x = Konzern_ID, 
                  fill = Konzern_Fraktion, color = Konzern_Fraktion)) +
  geom_bar(alpha = 0.4) +
  scale_fill_manual(values = kon_colors) +
  scale_color_manual(values = kon_colors) +
  labs(x = "", y = "Spiele") +
  facet_wrap(~Konzern_Fraktion, scales = "free_x", ncol = 4) +
  theme(axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1),
        legend.position = "none")
```

```{r IDs_Runner}
ggplot(s4, aes(x = Runner_ID, 
                  fill = Runner_Fraktion, color = Runner_Fraktion)) +
  geom_bar(alpha = 0.4) +
  scale_fill_manual(values = run_colors) +
  scale_color_manual(values = run_colors) +
  labs(x = "", y = "Spiele") +
  facet_wrap(~Runner_Fraktion, scales = "free_x") +
  theme(axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1),
        legend.position = "none")
```

## Runs

### Runs pro Spieler

Der graue Balken ist die durchschnittliche Anzahl Runs über alle Spieler hinweg und die schwarzen Balken sind entsprechend der Durchschnitt der jeweiligen Person.

```{r Runs_Spieler}
ggplot(s4, aes(x = Runner_Player, y = Runs, color = Runner_Player)) +
  geom_hline(yintercept = mean(s4$Runs, na.rm = T), 
             size = 1, color = "gray") +
  stat_summary(fun.y = "mean", fun.ymax = "mean", fun.ymin = "mean", 
               colour = "black", size = 0.5, geom = "errorbar") +
  geom_jitter() +
  labs(x = NULL, y = "Runs") + 
  theme(legend.position = "none")
```