---
title: "Spielwiese"
author: "Tobias Anton"
date: "11-11-11"
output:
  rmdformats::html_clean:
  # html_document:
    fig_width: 10
    dpi: 360
    highlight: tango
    theme: spacelab
---

```{r, message=F, warning=FALSE, include=FALSE}
source(paste0(Sys.getenv("PROJECT_HOME"), "./init.R"))
knitr::opts_chunk$set(echo = F, fig.path = "plots/", warning = F, message = F)
```

# Spielwiese

### data manipulation & exploration

```{r, manipulation, echo = T}
liga <- liga %>% 
  mutate("Schnitt_Zug" = (Dauer / Runden))


ggplot(liga, aes(x = Dauer, y = Schnitt_Zug)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = F) +
  scale_color_brewer(palette = "Set1") + 
  theme_tufte()
```

### Interaktive Plots

```{r, fig.height=18, message=F, warning=F, chunky-chunk, echo=T, eval = F}
  library(viridisLite)

    highscore <- score %>% select(Spiel, Spieler)
    
    highscore <- table(highscore$Spiel, highscore$Spieler)
    
    highscore <- as.data.frame.matrix(crossprod(highscore))
  
    
    gradient <- color_tile("white", "red")
    
    format_table(highscore, 
                 list(Bjarne = gradient, Bodo = gradient, Falk = gradient,
                      Jan = gradient, Johannes = gradient, Josh = gradient,
                      Kai = gradient, Paul = gradient, Tobias = gradient), 
                 check.rows = F, align = "c", format = "markdown")
    
    
    liga %>% 
  group_by(Spieler) %>% 
  summarize(Spiele = n()/2,
            "Agendapunkte / Spiel" = sum(Agendapunkte) / (n()/2),
            "Punkte pro Spiel"     = sum(Punkte) / (n()/2),
            Kills  = filter(Seite == "Konzern", Siegbedingung == "Flatline") %>% count(Spieler)$n)
```

### Unconventional ggPlotting

```{r unconventional_ggPlotting}

seiten <- score %>% 
  group_by(Spieler, Seite) %>% 
  summarize("perc" = ((sum(Punkte)/2)/n()) * 100) %>% 
  spread(Seite, perc) %>% 
  mutate(Runner = Runner * (-1)) %>% 
  gather(Seite, perc, Konzern, Runner) %>% 
  filter(perc == !is.na(T))

seiten <- seiten %>% filter(Seite == "Konzern")

ggplot(seiten, aes(x = Spieler, y = perc, fill = Seite)) +
  geom_bar(stat = "identity", position = "identity", color = "black") +
  coord_flip() + 
  scale_fill_manual(values = c("blue", "red")) +
  labs(x = NULL, y = "Siege pro Seite (%)") +
  scale_y_continuous(breaks = seq(-100, 100, 10)) +
  theme_update()

seiten <- score %>% 
  group_by(Spieler, Seite) %>% 
  summarize(N = n()/n())

seiten <- score %>% group_by(Spieler) %>% mutate(hundert = (n() / n()) * 100)

ggplot(score, aes(x = Spieler, fill = Seite)) +
  geom_bar(aes(y = (..count..)/sum(..count..)), color = "black") +
  coord_flip()
```