---
title: "Spielwiese"
author: "Tobias Anton"
date: "11-11-11"
output:
  rmdformats::html_clean:
  # html_document:
    fig_width: 10
    dpi: 520
    highlight: tango
    theme: flatly
---

```{r, message=F, warning=FALSE, include=FALSE}
source(paste0(Sys.getenv("PROJECT_HOME"), "./init.R"))
knitr::opts_chunk$set(echo = F, fig.path = "plots/", warning = F, message = F)

liga_03         <- filter(liga, Saison == 3)
runner_liga_03  <- filter(runner_liga, Saison == 3)
konzern_liga_03 <- filter(konzern_liga, Saison == 3)
```

# data manipulation & exploration

## cluster analysis

```{r, manipulation, echo = T}
# lets try cluster analysis!

cls <- runner_liga_03 %>% select(Archiv, `R&D`, HQ, Remote) %>% scale()

fit <- kmeans(cls, 4)

aggregate(cls, by = list(fit$cluster), FUN = mean)

cls <- data.frame(cls, fit$cluster)

library(cluster) 
clusplot(cls, fit$cluster, color=TRUE, shade=TRUE, 
  	labels=2, lines=0)

```

## Ole's accesses idee

```{r, accesses}
data <- data.frame(Faction = c("Shaper", "Shaper", "Criminals", "Criminals", "Anarchs", "Anarchs"),
                   HQ      = c("1,2,1", "0,1,1,0", 
                               "0,1,1,2,2", "0,2,2,0,0,1,3",
                               "0,1", "1,0,0"),
                   RnD     = c("0,1,1,2,2", "0,2,2,0,0,1,3",
                               "0,1", "1,0,0",
                               "1,2,1", "0,1,1,0"))
```

## Spielübersicht plot.ly

```{r, plotlybersicht}
## demo code
library(dplyr)
library(reshape2)
library(plotly)

p <- volcano %>%
  melt() %>% 
  ggplot(aes(Var1, Var2, fill = value)) + geom_tile()
  
ggplotly(p)
##  ##  ##  ##  ##  ##

ply <- as.data.frame.matrix(crossprod(table(score$Spiel, score$Spieler))) %>% 
  gather(Spieler, Spiele, Andi, Aschkan, Bjarne, Bodo, Boray, Falk, Jan,
         Johannes, Josh, `Josh R.`, Kai, Ole, Paul, Tobias) %>% 
  mutate(Gegner = rep(unique(Spieler), length(unique(Spieler)))) %>% 
  filter(Spieler != Gegner, Spiele != 0) %>% 
  ggplot(., aes(x = Spieler, y = Gegner, fill = Spiele)) + geom_tile()
    geom_tile(color = "white", size = 0.5, alpha = 0.9)
```

## Highcharterei

```{r highcharterei}
library(highcharter)

# highchart() %>% 
#   hc_yAxis(categories = step3$Gegensatz) %>% 
#   hc_add_series(data = step3$Studieren, type = "line", name = "Studieren") %>% 
#   hc_add_series(data = step3$Lernen, type = "line", name = "Lernen") %>% 
#   hc_add_series(data = step3$`forschendes Lernen`, type = "line", 
#                 name = "forschendes Lernen") %>% 
#   hc_add_series(data = step3$`forschendes Studieren`, type = "line", 
#                 name = "forschendes Studieren") %>% 
#   hc_add_series(data = step3$`forschungsorientiertes Lernen`, type = "line", 
#                 name = "forschungsorientiertes Lernen") %>% 
#   hc_add_series(data = step3$`forschungsbasiertes Lernen`, type = "line", 
#                 name = "forschungsbasiertes Lernen") %>% 
#   hc_title(text = "Mittlere Einschätzung der Konstrukte ") %>% 
#   hc_legend(layout = "vertical", verticalAlign = "top", align = "right")
# 
# hchart(step2, "line", x = Gegensatz, y = Wert, group = Konstrukt) %>% 
#   hc_legend(layout = "vertical", verticalAlign = "top", align = "right")


# simpel
hchart(runner_liga_03, "point", x = Spieler, y = Runs)

# komplex
highchart() %>% 
  hc_xAxis(categories = runner_liga_03$Spieler) %>% 
  hc_add_series(data = runner_liga_03$Runs, type = "point", name = "Runs")
```